added checks for deleted file(s), rm jshint comments

diff --git a/git/pre-commit b/git/pre-commit
--- a/git/pre-commit
+++ b/git/pre-commit
@@ -1,17 +1,20 @@
-#!/bin/sh
+#!/bin/bash
+# http://ariya.ofilabs.com/2012/10/javascript-validator-with-esprima.html
+#
+# added checks for
+#  - esvalidate is in $PATH
+#  - file was not removed
 
-# todo - breaks on file renames
-
-#which jshint >/dev/null || exit 0
 which esvalidate >/dev/null || exit 0
 
-# http://ariya.ofilabs.com/2012/10/javascript-validator-with-esprima.html
-#for file in $(git diff-index --name-only HEAD | egrep '\.js|json$')
-for file in $(git diff-index --name-only HEAD | egrep '\.js$')
+git diff-index --name-status HEAD | egrep '\.js$' | while read status file
 do
-    esvalidate $file || {
-        echo "Syntax error: $file"
-        exit 1
-    }
-    #jslint --extra-ext=.json $file || exit 1
+    if [[ ! $status =~ ^D ]]
+    then
+        esvalidate $file || {
+            echo "Syntax error: $file"
+            exit 1
+        }
+        echo "$status $file -> esvalidate ok"
+    fi
 done
